apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.durp.info/durfy/homelab/gitops.git
    targetRevision: main
    path: infra/istio-system
  destination:
    namespace: istio-system
    name: in-cluster
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        topology.istio.io/network: network1
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/failurePolicy

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-system-dmz
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.durp.info/durfy/homelab/gitops.git
    targetRevision: main
    path: dmz/istio-system
  destination:
    namespace: istio-system
    name: dmz
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        topology.istio.io/network: network2
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/failurePolicy
