apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.durp.info/durfy/homelab/gitops.git
    targetRevision: main
    path: infra/longhorn
  destination:
    namespace: longhorn-system
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: engineimages.longhorn.io
      jsonPointers:
        - /spec/preserveUnknownFields
      kind: CustomResourceDefinition

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-system-dmz
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.durp.info/durfy/homelab/gitops.git
    targetRevision: main
    path: dmz/longhorn
  destination:
    namespace: longhorn-system
    name: dmz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
