apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openspeedtest
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.durp.info/durfy/homelab/gitops.git
    targetRevision: main
    path: dmz/openspeedtest
    directory:
      recurse: true
  destination:
    name: dmz
    namespace: openspeedtest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
