apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-config-secret
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: renovate-config-secret
  data:
    - secretKey: renovate.json
      remoteRef:
        key: kv/renovate
        property: config
    - secretKey: RENOVATE_AUTODISCOVER
      remoteRef:
        key: kv/renovate
        property: RENOVATE_AUTODISCOVER
    - secretKey: RENOVATE_ENDPOINT
      remoteRef:
        key: kv/renovate
        property: RENOVATE_ENDPOINT
    - secretKey: RENOVATE_GIT_AUTHOR
      remoteRef:
        key: kv/renovate
        property: RENOVATE_GIT_AUTHOR
    - secretKey: RENOVATE_PLATFORM
      remoteRef:
        key: kv/renovate
        property: RENOVATE_PLATFORM
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: kv/renovate
        property: RENOVATE_TOKEN

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-personal-config-secret
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: renovate-personal-config-secret
  data:
    - secretKey: renovate.json
      remoteRef:
        key: kv/renoatePersonal
        property: config
    - secretKey: RENOVATE_AUTODISCOVER
      remoteRef:
        key: kv/renoatePersonal
        property: RENOVATE_AUTODISCOVER
    - secretKey: RENOVATE_ENDPOINT
      remoteRef:
        key: kv/renoatePersonal
        property: RENOVATE_ENDPOINT
    - secretKey: RENOVATE_GIT_AUTHOR
      remoteRef:
        key: kv/renoatePersonal
        property: RENOVATE_GIT_AUTHOR
    - secretKey: RENOVATE_PLATFORM
      remoteRef:
        key: kv/renoatePersonal
        property: RENOVATE_PLATFORM
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: kv/renoatePersonal
        property: RENOVATE_TOKEN
