#apiVersion: v1
#kind: Service
#metadata:
#  name: gitlab-ssh
#spec:
#  ports:
#    - name: app
#      port: 9022
#      protocol: TCP
#      targetPort: 9022
#  clusterIP: None
#  type: ClusterIP
#
#---
#apiVersion: v1
#kind: Endpoints
#metadata:
#  name: gitlab-ssh
#subsets:
#  - addresses:
#      - ip: 192.168.21.200
#    ports:
#      - name: app
#        port: 9022
#        protocol: TCP
#
#---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: gitlab-ssh
spec:
  entryPoints:
    - gitlab-ssh
  routes:
    - match: HostSNI(`*`)
      services:
        - name: unraid
          port: 9022

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`gitlab.durp.info`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: unraid
          port: 9443
          scheme: https
  tls:
    secretName: gitlab-tls

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-tls
spec:
  secretName: gitlab-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "gitlab.durp.info"
  dnsNames:
    - "gitlab.durp.info"

---
kind: Service
apiVersion: v1
metadata:
  name: gitlab-external-dns
  annotations:
    external-dns.alpha.kubernetes.io/hostname: gitlab.durp.info
spec:
  type: ExternalName
  externalName: durp.info
