apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`minio.internal.durp.info`) && PathPrefix(`/`)
      middlewares:
        - name: whitelist
          namespace: traefik
      kind: Rule
      services:
        - name: unraid
          port: 9769
          scheme: http
  tls:
    secretName: minio-tls

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-tls
spec:
  secretName: minio-tls
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  commonName: "minio.internal.durp.info"
  dnsNames:
    - "minio.internal.durp.info"
